// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  articlefourslice: dynamic(() => import("./Articlefourslice")),
  articleoneslice: dynamic(() => import("./Articleoneslice")),
  articlethreeslice: dynamic(() => import("./Articlethreeslice")),
  articletwoslice: dynamic(() => import("./Articletwoslice")),
  trending3_slice: dynamic(() => import("./Trending3Slice")),
  trendingfourslice: dynamic(() => import("./Trendingfourslice")),
  trendingoneslice: dynamic(() => import("./Trendingoneslice")),
  trendingthree_slice: dynamic(() => import("./TrendingthreeSlice")),
  trendingtwoslice: dynamic(() => import("./Trendingtwoslice")),
};
