import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Layout from '@/components/Layout'
import Prismic from "prismic-javascript"
import { RichText } from 'prismic-reactjs'
import Link from 'next/link'
import { Client } from "@/prismic-configuration";
import { PrismicText } from '@prismicio/react'
const inter = Inter({ subsets: ['latin'] })

export default function Sports({ article4, trending4 }) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <div className='container_trending'>
                    <h1 className='trending_layout_title'>See What's happening around the world</h1>
                    <div className='rough_trending_container'>
                        <p>We use cookies to run our website, analyze your use of our services, manage your online preferences & personalize ad content. By accepting our cookies, you'll get relevant content and social media features, personalized ads, and an enhanced browsing experience. To manage your choices, click “Cookie Settings.” Necessary cookies are required for the core website functionality and cannot be rejected. </p>
                    </div>
                    <button onClick={() => {
                        window.history.back();
                    }}>Go Back</button>
                </div>

            </Layout>
        </>
    )
}

// this function is called everytime when request is made or refresh

export async function getServerSideProps() {
    const trending4 = await Client().query(Prismic.Predicates.at("document.type", "trending4"));
    console.log(trending4)
    return {
        props: {
            trending4: trending4,

        }
    }
}