import Head from 'next/head'
import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'
import Layout from '@/components/Layout'
import Prismic from "prismic-javascript"
import { RichText } from 'prismic-reactjs'
import Link from 'next/link'
import { Client } from "@/prismic-configuration";
import { PrismicText } from '@prismicio/react'
const inter = Inter({ subsets: ['latin'] })

export default function Politics({ article2, trending2 }) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <div className='flex_rough'>
                    <div>
                        <div className='rough_article'>
                            {
                                article2.results.map((article, index) => (
                                    <>
                                        <h1>----------</h1>


                                        {article.data.slices.map((slice, sliceIndex) => (
                                            <div key={slice.uid}>
                                                {slice.items.map((item, index) => (
                                                    <img src={item.article2sliceimage.url} width={500} height={300} />
                                                ))}
                                            </div>
                                        ))}
                                        <p className='article_rough_content'>{article.data.article2text}</p>
                                    </>
                                ))
                            }
                        </div>
                        <div className='rough_article'>
                            {
                                article2.results.map((article, index) => (
                                    <>
                                        <h1>----------</h1>
                                        {article.data.slices.map((slice, sliceIndex) => (
                                            <div key={slice.uid}>
                                                {slice.items.map((item, index) => (
                                                    <img src={item.article2sliceimage.url} width={500} height={300} />
                                                ))}
                                            </div>
                                        ))}
                                        <p className='article_rough_content'>{article.data.article2text}</p>
                                    </>
                                ))
                            }
                        </div>
                        <button className='article_rough_button' onClick={() => {
                            window.history.back();
                        }}>Go Back</button>
                    </div>
                </div>
            </Layout>
        </>
    )
}


// this function is called everytime when request is made or refresh

export async function getServerSideProps() {
    const article2 = await Client().query(Prismic.Predicates.at("document.type", "article2"));
    return {
        props: {
            article2: article2,

        }
    }
}